# Generated by Django 5.0.3 on 2024-04-17 15:48

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Объявление'),
        ),
    ]
