# Generated by Django 5.0.3 on 2024-04-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_advertisement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='board.advertisement', verbose_name='Объявление'),
        ),
    ]
